const router = require("express").Router()
const cors = require("cors")

const auth = require("../routes/auth")
const airports = require("../routes/airports")
const users = require("../routes/users")
const docs = require("../routes/docs")
const flights = require("../routes/flights")
const destination = require("../routes/destinations")
const passengers = require("../routes/passengers")
const bookings = require("../routes/bookings")
const seats = require("../routes/seats")
const checkout = require("../routes/checkout")
const history = require("../routes/history")
const notification = require("../routes/notification")
const boardingPass = require("../routes/boardingPass")
const whislist = require("../routes/whislist")

router.use(cors())
router.use("/api/", auth)
router.use("/api/airports/", airports)
router.use("/api/users/", users)
router.use("/api/destinations/", destination)
router.use("/api/passenger/", passengers)
router.use("/api/flights/", flights)
router.use("/api/bookings/", bookings)
router.use("/api/seats/", seats)
router.use("/api/checkout/", checkout)
router.use("/api/", history)
router.use("/api/notification", notification)
router.use("/api/boardingPass", boardingPass)
router.use("/api/whislist", whislist)
router.use("/api-docs", docs)

module.exports = router
