name: Lint and Test Before Merge 
on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - release
jobs:
  lint:
    environment: testing
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
  test:    
    environment: testing
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      IMAGEKIT_PUBLIC_KEY: public_JgOc3/fk9JH1NWwgeLM2jXHinWE=
      IMAGEKIT_PRIVATE_KEY: private_m89J9THR3+r25s5NupBcprZsa/g=
      IMAGEKIT_URL: ${{ secrets.IMAGEKIT_URL }}
      PORT: 8080
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json
  merge:
    needs: [test, lint]
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Merge
        run: echo "Can Be Merge..."